general:
  name: mos_target_opsdb_apo_configuration
  short: replace me - with a short one sentence summary of file
  description: replace me - with a longer description of the data product
  datatype: FITS
  filesize: 523 KB
  releases:
  - DR19
  environments:
  - MOS_TARGET
  surveys:
  - SDSS
  naming_convention: replace me - with $MOS_TARGET/[V_TARG]/mos_opsdb_apo_configuration.fits
    or mos_opsdb_apo_configuration.fits but with regex pattern matches
  generated_by: replace me - with the name(s) of any git or svn product(s) that produces
    this product.
  data_level: 2.3.3
  design: false
  vac: false
  recommended_science_product: false
changelog:
  description: Describes changes to the datamodel product and/or file structure from
    one release to another
  releases: {}
releases:
  DR19:
    template: $MOS_TARGET/[V_TARG]/mos_opsdb_apo_configuration.fits
    example: 1.0.2/mos_opsdb_apo_configuration.fits
    location: '{v_targ}/mos_opsdb_apo_configuration.fits'
    environment: MOS_TARGET
    access:
      in_sdss_access: false
      path_name: null
      path_template: null
      path_kwargs: null
      access_string: mos_target_opsdb_apo_configuration = $MOS_TARGET/{v_targ}/mos_opsdb_apo_configuration.fits
    survey: SDSS
    hdus:
      hdu0:
        name: PRIMARY
        description: replace me description
        is_image: true
        size: 0 bytes
        header:
        - key: SIMPLE
          value: true
          comment: conforms to FITS standard
        - key: BITPIX
          value: 8
          comment: array data type
        - key: NAXIS
          value: 0
          comment: number of array dimensions
        - key: EXTEND
          value: true
          comment: ''
      hdu1:
        name: ''
        description: replace me description
        is_image: false
        size: 517 KB
        header:
        - key: XTENSION
          value: BINTABLE
          comment: binary table extension
        - key: BITPIX
          value: 8
          comment: array data type
        - key: NAXIS
          value: 2
          comment: number of array dimensions
        - key: NAXIS1
          value: 58
          comment: length of dimension 1
        - key: NAXIS2
          value: 9134
          comment: length of dimension 2
        - key: PCOUNT
          value: 0
          comment: number of group parameters
        - key: GCOUNT
          value: 1
          comment: number of groups
        - key: TFIELDS
          value: 6
          comment: number of table fields
        - key: TNULL1
          value: -2147483648
          comment: ''
        - key: TNULL2
          value: -2147483648
          comment: ''
        columns:
          configuration_id:
            name: configuration_id
            type: int32
            unit: replace me - with content
            description: replace me - with content
          design_id:
            name: design_id
            type: int32
            unit: replace me - with content
            description: replace me - with content
          comment:
            name: comment
            type: char[4]
            unit: replace me - with content
            description: replace me - with content
          temperature:
            name: temperature
            type: char[4]
            unit: replace me - with content
            description: replace me - with content
          epoch:
            name: epoch
            type: float64
            unit: replace me - with content
            description: replace me - with content
          calibration_version:
            name: calibration_version
            type: char[34]
            unit: replace me - with content
            description: replace me - with content
notes: |-
  None
regrets: |-
  I  have no regrets!
