general:
  name: mos_target_opsdb_apo_configuration
  short: 'MOS Target table: mos_target_opsdb_apo_configuration'
  description: This table contains basic information about a configuration of robots
    loaded at the telescope.
  datatype: FITS
  filesize: 523 KB
  releases:
  - DR19
  environments:
  - MOS_TARGET
  surveys:
  - BHM
  - MWM
  - SDSS
  naming_convention: $MOS_TARGET/[V_TARG]/mos_opsdb_apo_configuration.fits, where
    V_TARG=1.0.2 for DR19
  generated_by: sdss5db> targetdb, operations database server
  data_level: 2.3.3
  design: false
  vac: false
  recommended_science_product: false
changelog:
  description: Describes changes to the datamodel product and/or file structure from
    one release to another
  releases: {}
releases:
  DR19:
    template: $MOS_TARGET/[V_TARG]/mos_opsdb_apo_configuration.fits
    example: 1.0.2/mos_opsdb_apo_configuration.fits
    location: '{v_targ}/mos_opsdb_apo_configuration.fits'
    environment: MOS_TARGET
    access:
      in_sdss_access: true
      path_name: mos_target_opsdb_apo_configuration
      path_template: $MOS_TARGET/{v_targ}/mos_opsdb_apo_configuration.fits
      path_kwargs:
      - v_targ
      access_string: mos_target_opsdb_apo_configuration = $MOS_TARGET/{v_targ}/mos_opsdb_apo_configuration.fits
    survey: SDSS
    hdus:
      hdu0:
        name: PRIMARY
        description: Primary header
        is_image: true
        size: 0 bytes
        header:
        - key: SIMPLE
          value: true
          comment: conforms to FITS standard
        - key: BITPIX
          value: 8
          comment: array data type
        - key: NAXIS
          value: 0
          comment: number of array dimensions
        - key: EXTEND
          value: true
          comment: ''
      hdu1:
        name: ''
        description: 'MOS Target table: mos_target_opsdb_apo_configuration'
        is_image: false
        size: 517 KB
        header:
        - key: XTENSION
          value: BINTABLE
          comment: binary table extension
        - key: BITPIX
          value: 8
          comment: array data type
        - key: NAXIS
          value: 2
          comment: number of array dimensions
        - key: NAXIS1
          value: 58
          comment: length of dimension 1
        - key: NAXIS2
          value: 9134
          comment: length of dimension 2
        - key: PCOUNT
          value: 0
          comment: number of group parameters
        - key: GCOUNT
          value: 1
          comment: number of groups
        - key: TFIELDS
          value: 6
          comment: number of table fields
        - key: TNULL1
          value: -2147483648
          comment: ''
        - key: TNULL2
          value: -2147483648
          comment: ''
        columns:
          configuration_id:
            name: configuration_id
            type: int32
            unit: ''
            description: Unique identifier
          design_id:
            name: design_id
            type: int32
            unit: ''
            description: Unique identifier of the design loaded
          comment:
            name: comment
            type: char[4]
            unit: ''
            description: An optional comment
          temperature:
            name: temperature
            type: char[4]
            unit: ''
            description: The ambient temperature when the design was loaded
          epoch:
            name: epoch
            type: float64
            unit: ''
            description: The Julian Date (JD) when the design was loaded
          calibration_version:
            name: calibration_version
            type: char[34]
            unit: ''
            description: The version of fps_calibration used, https://github.com/sdss/fps_calibrations/tags
notes: |-
  None
regrets: |-
  I  have no regrets!
