name: Build and Deploy Sphinx to Pages

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          pip install -e .[docs]

      - name: Generate product links
        run: |
          python docs/generate_mds.py

      - name: Build Sphinx docs
        run: |
          cd "docs/sphinx/"
          make html

      - name: Package artifacts
        run: |
          mkdir -p artifact/docs/sphinx
          mkdir -p artifact/datamodel/products/md
          cp -r docs/sphinx/_build/html/* artifact/docs/sphinx/
          cp docs/product_files.md artifact/docs/
          cp docs/README.md artifact/docs/
          cp -r datamodel/products/md artifact/datamodel/products/md

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          name: github-pages
          path: artifact/

  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: github-pages
          path: artifact/

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact-name: github-pages
          publish-dir: artifact/docs
