name: Build and Deploy Sphinx to Pages

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - pages
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          pip install -e ".[docs, all]"

      - name: Generate product links
        run: |
          python docs/generate_mds.py

      - name: Build Sphinx docs
        run: |
          cd "docs/sphinx/"
          make html

      - name: Package artifacts
        run: |
          mkdir -p artifact/sphinx
          mkdir -p artifact/datamodel/products/md
          cp -r docs/sphinx/_build/html/* artifact/sphinx/
          cp docs/product_files.md artifact/
          cp docs/README.md artifact/
          cp -r datamodel/products/md/* artifact/datamodel/products/md
          echo "<html><body><h1>Welcome to the Documentation</h1><p><a href='README.md'>Read Me</a></p><p><a href='sphinx/index.html'>Sphinx</a></p></body></html>" > artifact/index.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./artifact

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write
      contents: read

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        id: deployment
