name: Build Sphinx Docs

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push, pull_request]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.allow_failure }}

    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]
        allow_failure: [false]
        os: [ubuntu-latest]
        include:
          - python: 3.10
            os: ubuntu-latest
            allow_failure: true

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # setup python version
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    # Run a sphinx build test
    - name: Sphinx Build
      uses: ammaraskar/sphinx-action@0.4
      with:
        # The folder containing your sphinx docs.
        docs-folder: "docs/sphinx/"  # default is docs/
        # The command used to build your documentation.
        build-command: make html  # optional, default is make html
        # Pre-build command
        pre-build-command: "apt-get update -y && apt-get install -y gcc && pip install .[docs]"
